@baseUrl = http://localhost:5000/
@admin = { username: "admin", Role: "Admin" }

###
POST {{baseUrl}}auth HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

GET {{baseUrl}}issue HTTP/1.1
content-type: application/json
user-token: { "username": "admin", "Role": "Admin" }